language: php
php:
  - 5.3
  - 5.4
  
before_script:  
  # Installing pecl_http Module
  - printf "\n\n\n\n" | pecl -q install pecl_http
  - echo "extension=http.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"` 
  
  # Install composer for dependency management
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install